language: scala

scala:
  - 2.12.2
  - 2.11.11

script:
#  - sbt clean test
  - sbt ++$TRAVIS_SCALA_VERSION clean test

jdk:
  - oraclejdk8

env:
  global:
    _ secure: "lZtIHqOrN5yhavNu/59ogmID8vgrUkkBlxsj1vSqNolnei8RW74iOhhCzKj0vT052zcg3GyhkTG0s4g5zRHyE26bLCQkBqCm5LhUcSX50+zFIFiK3ahZRam1axzFdm3pI8QYEU+tPNrqkwPCp+r6p/2LsCO6juL0gCx4ZTssTRTLYfBSM3HXtHDtbkZBePy3AhD25Rw4XrlkCNMepwEYzvlVjTvK/HVWVg+fWymADs5qZ7oX9dUuk8gTSa3arQ/44ZKJr1VFvQhIczzMgzmndEws4blF1yJBls5AMrH9L92LrRZ/CWe3qqgRdbOSgvhzFPR8THFWB5Eb6GpBObxC+ULoSzfNJhvqjCt7cQcMj0mhUrAq/y5PUnfFWRRZS8hveC0klNZuAy4SZIgeK0JgZpV480XBWuDo/tYpy4EX/V1j66oHr3gQPU3rGXRWl5DXTZTN9XqblU1Sz5QpfMarqXGlW4rteyEXA90Hu/tAMISh68lp7YCG9zzIIADwnBP41dR7lVMTrZlSpQOL4XI4gAnsNpo5MiENegQslsFF/UcvGYni/Q8D/0aSbCzFT1gg6WLDknvB4F86l/xzb26rdNu0b8G3+/ger+VVRTLr/TV7e8a7fr0rJ+A/cZTcH111T5FNf3YO0Zq4FsHrI+hMM+4aIOQFVSnC0WOsJUix6rM="
    _ secure: "EofTIUalWHe7ZmxG5izdHSYeYG6yngb1J+8O1dwIX76hxgu9nEBEs/jOa/oRO0RBxpM3nfH/IesD/0CzJOFg4mXXUPkIscciTi4ZG8dn3z+Gdy8KZN1OoSs//kwwNykpBRpYBCn7McWMhvOY8lxb2Y95Ex8L11mqveitb+9QC6ymsMA7D/qfAsoDy7YykXhNDug6qbJwFd4oXwnuzSBWqXcrakYt52nvXodrfeYEnKMlhU5AL9BnmWJMU/9HsdZ/lSkrfwikRL7c7AlLRNE1pcKQCNol8MqOUH6B8qz2I8K2yhnGK4T/EKTpppyPVgho7bQeGIwAUVwcLoditDvbGfQHYH3XJAdny0EEYOugzArjVDjX2U5JgpYV1xUeQ5eKGrn+Z6q2i+9EjrUZgDoAwHWNz9MWRf68gpX2jGjGKPeBOT6786N0cAdm7qudJFKZyGNgMdsvrMh6nvK+KVKFDFsQC+a3Onty5hUGen2CnQz3fGdhgSEwOd4Oa3yLOmtwT5I2sXzhxI47FHEV9b8wea6VjDZcrzW7pSpr5ij5M1iniD7XCVs05GWFCIMeifDwopUj3tV+M7T69Ztg7PBr6GiATfNGm3fylYpWhLK5Pe4zktIleHHGX/HhWRkb3GCusl7/cS/cBa9bd+695BkdGz85N9y8jR/GekpZXWEy7rM="

after_success:
  - "[[ $TRAVIS_BRANCH == \"master\" ]] && { sbt ++$TRAVIS_SCALA_VERSION publish; };"
