language: scala
scala:
- 2.12.2
- 2.11.11
script:
- sbt ++$TRAVIS_SCALA_VERSION clean test
jdk:
- oraclejdk8
env:
  global:
  - secure: h+MjrVRstiU+Q/fgDtuPCGiHnf6c8Mac54i61eN6M3w5IJXwOpYoTKVWxBo9uTXMplYTXydUCwydk2NEjoAiWzd+gxYAZ+pl9BIRSqPhmX4dY+/4o0aha/hNohv3itCuy/HKSgRt35w4T1uE9wwxCvzUA8khqmXhxSNqXx3w+/NsJ1hFIlCwMcIzS5Z7/iNdFk4ZBspdwEsIrwxjkdWlihfhMIVBpAjSQuyxVEL/LSCk0wPOe0W4NpPPEPVCLRNe6eErrly428n/6EgE1+18/Sh9WENySZ+YryNF61BL5PNXTeK+xMPUSD7T78YNuM+lxURIqo7xhimJBZzJ2p4kGiDc9CNjA5Leu5jVJFivAdWX5Wd30CeR8AafN2zAo3FWjhS1rMVIfIp5yjdsUXVaGm7HiRPEIbukS79QW3cAbarEvQRypETY3NM9vlKuAQHOw7f6vWPlY5nsraUCtFMM21vAlIJ8M5F2JQXvC0LCb35MJMQssIXCs2VC5mpYQdO7q+15ZRcuyA/06HlGLj4cm1beWkPp3imz66Z1jxbOUN+DayKH+++XgccUGAZp2FhMX4tXR7vh/Atb42Wr8W2hzC8e4XmnZRIZIHSfiTIVrhViDlo+ZHbJcUd6hZs00MY/Y32xiBs0Rig7qbqdDH11URDjJGacIcd8IT3H1ntkFow=
  - secure: a6+a/mKMkXUhidt/Bk0/IFar8F4I1yLMhmcD20DIc6VKznGOX212Ksx0GXqjuBjaeph8V3byWN/MLSYecDRFMW8IXx/tf1UqqeabpS09jxTATktar0Z1MS7AQ8q2SyRhnaVHEv/vlxB8ti5JhxlvVuoOZ6pNsiEpow2F0PvrLyzJXATIjMTFPI27OZq1K55WXdDFb+heLvhiRgk6rP4RpgcAs4+1eK1TwxQTDTY13A5Z0q6yJ3BmA5jpPbw9N0dycc9gl3ax6n0+vV0ecXm5yxNwzJ71mPx7G3Z4r8dq07EsqKfX60PkiuUv3V5azg9u5QY+KBPB107IIfTytM1na7EIIGfhO64paDhJ9qOlCGzg17dZ/yky0nbC0rC4PqQPgmCl/V0iKpyRdrdchvbyKNZ+HGySU/VIZBbX/4kNoEPec5Z5lhOjCNjF2neA0CuVI+Bb2ijEliYsCu9M6fqh+HQ6TOIAruqYmamUr+PjWdNrM3TuxVA6XaAIjYA8QcJ4XCZT/q2W7ACtqBsqMRp5PmT2srARP517p7R7D82o8mY6SDYHBbucmgLGqbC8lZ6LVdVhGmYdfR35y+vFI7T1BcNvdWVieRgvpXKutnwrIFrJS/9qbeWVrBy9o2BrG+8qKUoigdw195OZifbNvRHYbmddiP6GLVP3taPdygjzuQc=

after_success:
- '[[ $TRAVIS_BRANCH == "master" ]] && { sbt ++$TRAVIS_SCALA_VERSION publish; };'
